INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (1, 'In which country would you find the Leaning Tower of Pisa?', 'Italy');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (1, 'Which planet is nearest to the Earth?', 'Venus');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (1, 'Which is the coldest place on Earth?', 'Antarctica');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (1, 'Which river flows through the rainforest in brazil?', 'Amazon');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (1, 'Which is the most populous city in the United Kingdom which is also its capital city?', 'London');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (2, 'In The Matrix, does Neo take the blue pill or the red pill?', 'red');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (2, 'For what movie did Tom Hanks score his first Academy Award nomination?', 'big');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (2, 'What is the highest-grossing R-rated movie of all time?', 'Joker');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (2, 'Who captures Nemo at the beginning of Finding Nemo?', 'dentist');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (2, 'What kind of animal is Manny in Ice Age: The Meltdown?', 'mammoth');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (3, 'Which animal is known as mans best friend?', 'dog');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (3, 'What kind of fish is Nemo?', 'clownfish');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (3, 'Which bird is a symbol of peace?', 'dove');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (3, 'Which animal is the tallest in the world?', 'giraffe');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (3, 'What was the first bird domesticated by man?', 'goose');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (4, '2 + 2 =', '4');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (4, '20 + 20 =', '40');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (4, '200 + 200 =', '400');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (4, '6 * 7 =', '42');
INSERT INTO questionsAndAnswer (quiz_id, question, answer) VALUES (4, 'Stretch: sin 90 = ', '1');
