DROP TABLE IF EXISTS quizzes CASCADE;
CREATE TABLE quizzes (
    id SERIAL PRIMARY KEY NOT NULL, 
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT,
    private  BOOLEAN NOT NULL DEFAULT TRUE,
    url VARCHAR(255)
    );